CREATE DATABASE IF NOT EXISTS modulo_admin;
CREATE DATABASE IF NOT EXISTS modulo_compras;
CREATE DATABASE IF NOT EXISTS modulo_inventario;
CREATE DATABASE IF NOT EXISTS modulo_produtos;
CREATE DATABASE IF NOT EXISTS modulo_pessoas;
CREATE DATABASE IF NOT EXISTS modulo_producao;
CREATE DATABASE IF NOT EXISTS modulo_rh;
CREATE DATABASE IF NOT EXISTS modulo_vendas;
